### ISSUE TITLE
Support PHP 8 and drop support for php 7.3?

### ISSUE THREAD

**Issue by Potherca** [pdsinterop/php-solid-auth#19]
Our `pdsinterop/solid-auth` package uses [`lcobucci/jwt`](https://github.com/lcobucci/jwt) and is used in both the [Nextcloud](https://github.com/pdsinterop/solid-nextcloud) and [Standalone PHP](https://github.com/pdsinterop/php-solid-server/) Solid Servers.

When we started implementing Solid in PHP, in early/mid 2020, the lowest supported PHP version was 7.3 and the Nextcloud version was 20. Starting 2022, PHP 7.3 will no longer be supported (see https://www.php.net/supported-versions) and PHP 8.1 will have been released. As of last month Nextcloud 20 is also no longer supported.

The current Nextcloud releases support the following PHP versions:

| Nextcloud | 7.1 | 7.2 | 7.3 | 7.4 | 8.0 | 8.1 |
| --------: | --- | :---: | :---: | :---: | :---: | :---: |
|      `20`  |     |  ✅ |  ✔ |  ✔ |    |    |
|      `21`  |     |     |  ✅ |  ✅ |  ✔ |    |
|      `22`  |     |     |  ✅ |  ✅ |  ✔ |    |
|      [`23`][23]  |     |     |  ✅ |  ✅ |  ✔ |    |
|      [`24`][24]  |     |     |     |  ✅ |  ✔ | ✅  |
|      [`25`][25]  |     |     |     |  ✅ |  ✔ | ✅  |

✅ = supported
✔ = recommended

[23]: https://docs.nextcloud.com/server/23/admin_manual/installation/system_requirements.html
[24]: https://docs.nextcloud.com/server/24/admin_manual/installation/system_requirements.html
[25]: https://docs.nextcloud.com/server/stable/admin_manual/installation/system_requirements.html

We need to start supporting PHP 8, however, there is a problem related to `lcobucci/jwt`, specifically, the PHP versions supported by that library. Version 3 supports PHP7 _but not_ 8, version 4 supports PHP 8 but _only_ 7.4. (not 7.3).

This means that, if we  continue to use that package, we can support _either_ PHP 7.3 _or_  PHP 8, but **not both**.

My suggestion would be to drop support from PHP 7.3 so we can update all three of our libraries to `lcobucci/jwt` to v4 and start supporting PHP 8.

Companion issues have been opened in the Nextcloud and Standalone PHP repos for this issue:

- https://github.com/pdsinterop/php-solid-server/issues/56
- https://github.com/pdsinterop/solid-nextcloud/issues/59

**Comment by poef** [comment]
I think we should make a final version that supports 7.3 and nextcloud 20 and then make a new major release that drops 7.3 (and nextcloud 20) support

**Comment by Potherca** [comment]
Resolved in #20
